version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    volumes:
         - ./bd:/var/lib/postgresql/data
         - ./bd_backup:/data/bd_backup
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G