version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:12.10-bullseye
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test-admin-user"
      POSTGRES_PASSWORD: "netpass"
    volumes:
         - ./bd:/data/bd
         - ./bd_backup:/data/bd_backup
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G